name: FGVC_Swin
model_type: FGVC_PIM
num_gpu: auto
dataroot: F:\ImageData\CUB_200_2011\images
resize_size: 510
data_size: 384
auto_resume: 1
val_rate: 0.1


use_selection: True
use_amp: True
use_fpn: True
use_combiner: True
lambda_b: 0.5
lambda_s: 0.0
lambda_n: 5.0
lambda_c: 1.0

datasets:
  train:
    name: CUB_200_2011
    type: FGVCDataset
    batch_size_per_gpu: 1
    num_worker_per_gpu: 0
    
  val:
    name: CUB_200_2011_val
    type: FGVCDataset


network_g:
  type: SwinTransfomer
  pretrain: False
  use_checkpoint: True


path:
  pretrain_network_g: E:\swin_large_patch4_window12_384_22k.pth
  param_key_g: "model"
  strict_load_g: False
  resume_state: ~


train:
  ema_decay: 0.999
  warmup_iter: 800
  optim_g:
    type: SGD
    lr: !!float 5e-4
    # weight_decay: 0
    # betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [300000]
    restart_weights: [1]
    eta_min: !!float 1e-12
  
  CrossentropyLoss_opt:
    type: CrossentropyLoss
    loss_weight: 1.0


  total_epochs: 50
  warmup_iter: -1  # no warm up


val:
  val_freq: !!float 1e3
  save_img: false
  pbar: True

logger:
  print_freq: 10
  save_checkpoint_freq: 1000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

# find_unused_parameters: true